//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComputoHoras
{
    using System;
    using System.Collections.Generic;
    
    public partial class Imputaciones
    {
        public System.DateTime FECHA_IMPUTACION { get; set; }
        public Nullable<double> HORAS { get; set; }
        public long ID_TAREA { get; set; }
        public long ID_EMPLEADO { get; set; }
    }
}
